import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const prisma = new PrismaClient();

const standardExercises = [
  // STRENGTH - Compound Lifts
  {
    name: 'Barbell Back Squat',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'King of lower body exercises. Builds overall leg strength and power.',
    descriptionDE: 'König der Unterkörperübungen. Baut allgemeine Beinkraft und Kraft auf.',
  },
  {
    name: 'Barbell Front Squat',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=uYumuL_G_V0',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Front-loaded squat variation that emphasizes quads and core stability.',
    descriptionDE: 'Frontal belastete Kniebeuge-Variante, die Quadrizeps und Rumpfstabilität betont.',
  },
  {
    name: 'Deadlift',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    muscleGroups: ['legs', 'back', 'core'],
    descriptionEN: 'Essential posterior chain exercise. Builds total body strength.',
    descriptionDE: 'Wesentliche hintere Kettenübung. Baut Ganzkörperkraft auf.',
  },
  {
    name: 'Romanian Deadlift',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=2SHsk9AzdjA',
    muscleGroups: ['legs', 'back'],
    descriptionEN: 'Targets hamstrings and glutes with controlled hip hinge movement.',
    descriptionDE: 'Zielt auf Oberschenkelrückseite und Gesäß mit kontrollierter Hüftbewegung.',
  },
  {
    name: 'Barbell Bench Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    descriptionEN: 'Primary upper body pushing exercise for chest development.',
    descriptionDE: 'Primäre Oberkörper-Drückübung für Brustentwicklung.',
  },
  {
    name: 'Incline Barbell Bench Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=SrqOu55lrYU',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    descriptionEN: 'Targets upper chest with angled pressing movement.',
    descriptionDE: 'Zielt auf obere Brust mit abgewinkelter Drückbewegung.',
  },
  {
    name: 'Barbell Overhead Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    muscleGroups: ['shoulders', 'arms', 'core'],
    descriptionEN: 'Fundamental overhead pressing movement for shoulder strength.',
    descriptionDE: 'Grundlegende Überkopf-Drückbewegung für Schulterkraft.',
  },
  {
    name: 'Barbell Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Key horizontal pulling exercise for back thickness.',
    descriptionDE: 'Wichtige horizontale Zugübung für Rückendicke.',
  },
  {
    name: 'Pull-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Vertical pulling exercise using bodyweight for back and arm strength.',
    descriptionDE: 'Vertikale Zugübung mit Körpergewicht für Rücken- und Armkraft.',
  },
  {
    name: 'Chin-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=brhRXlOhkAM',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Underhand grip pull-up variation emphasizing biceps.',
    descriptionDE: 'Untergriff-Klimmzug-Variante mit Betonung auf Bizeps.',
  },

  // STRENGTH - Accessory Work
  {
    name: 'Dumbbell Bench Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=VmB1G1K7v94',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    descriptionEN: 'Allows greater range of motion than barbell for chest development.',
    descriptionDE: 'Ermöglicht größeren Bewegungsumfang als Langhantel für Brustentwicklung.',
  },
  {
    name: 'Dumbbell Shoulder Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
    muscleGroups: ['shoulders', 'arms'],
    descriptionEN: 'Unilateral shoulder pressing for balanced development.',
    descriptionDE: 'Einseitiges Schulterdrücken für ausgeglichene Entwicklung.',
  },
  {
    name: 'Dumbbell Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=roCP6wCXPqo',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Single-arm rowing movement for back development.',
    descriptionDE: 'Einarmige Ruderbewegung für Rückenentwicklung.',
  },
  {
    name: 'Lunges',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=QOVaHwm-Q6U',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Unilateral leg exercise for balance and strength.',
    descriptionDE: 'Einseitige Beinübung für Balance und Kraft.',
  },
  {
    name: 'Bulgarian Split Squat',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Advanced single-leg squat variation for leg strength.',
    descriptionDE: 'Fortgeschrittene Einbein-Kniebeuge-Variante für Beinkraft.',
  },
  {
    name: 'Leg Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    muscleGroups: ['legs'],
    descriptionEN: 'Machine-based leg exercise for quad and glute development.',
    descriptionDE: 'Maschinenbasierte Beinübung für Quadrizeps- und Gesäßentwicklung.',
  },
  {
    name: 'Leg Curl',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=ELOCsoDSmrg',
    muscleGroups: ['legs'],
    descriptionEN: 'Isolation exercise for hamstring development.',
    descriptionDE: 'Isolationsübung für Oberschenkelrückseitenentwicklung.',
  },
  {
    name: 'Leg Extension',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
    muscleGroups: ['legs'],
    descriptionEN: 'Isolation exercise for quadriceps development.',
    descriptionDE: 'Isolationsübung für Quadrizepsentwicklung.',
  },
  {
    name: 'Hip Thrust',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Glute-focused exercise for hip extension power.',
    descriptionDE: 'Gesäß-fokussierte Übung für Hüftstreckungskraft.',
  },
  {
    name: 'Cable Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Seated rowing exercise for mid-back development.',
    descriptionDE: 'Sitzende Ruderübung für mittlere Rückenentwicklung.',
  },
  {
    name: 'Lat Pulldown',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Machine-based vertical pulling for lat development.',
    descriptionDE: 'Maschinenbasiertes vertikales Ziehen für Latentwicklung.',
  },
  {
    name: 'Face Pulls',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    muscleGroups: ['shoulders', 'back'],
    descriptionEN: 'Cable exercise for rear deltoid and upper back health.',
    descriptionDE: 'Kabelübung für hintere Schulter und oberen Rücken.',
  },
  {
    name: 'Bicep Curls',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    muscleGroups: ['arms'],
    descriptionEN: 'Isolation exercise for bicep development.',
    descriptionDE: 'Isolationsübung für Bizepsentwicklung.',
  },
  {
    name: 'Tricep Dips',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=6kALZikXxLc',
    muscleGroups: ['arms', 'chest'],
    descriptionEN: 'Bodyweight exercise for tricep and chest development.',
    descriptionDE: 'Körpergewichtsübung für Trizeps- und Brustentwicklung.',
  },
  {
    name: 'Skull Crushers',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
    muscleGroups: ['arms'],
    descriptionEN: 'Lying tricep extension for arm strength.',
    descriptionDE: 'Liegende Trizepsstreckung für Armkraft.',
  },

  // PLYOMETRICS & POWER
  {
    name: 'Box Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=NBY9-kTuHEk',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Explosive jumping exercise for lower body power.',
    descriptionDE: 'Explosive Sprungübung für Unterkörperkraft.',
  },
  {
    name: 'Depth Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=qU35AOa_Gk0',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Advanced plyometric for reactive strength development.',
    descriptionDE: 'Fortgeschrittene Plyometrie für reaktive Kraftentwicklung.',
  },
  {
    name: 'Broad Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=MyvbIFToQHI',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Horizontal jumping for explosive power.',
    descriptionDE: 'Horizontales Springen für explosive Kraft.',
  },
  {
    name: 'Medicine Ball Slams',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=EXaYr1Ae8fk',
    muscleGroups: ['full-body', 'core'],
    descriptionEN: 'Full body explosive exercise for power and conditioning.',
    descriptionDE: 'Ganzkörper-explosive Übung für Kraft und Konditionierung.',
  },
  {
    name: 'Clap Push-ups',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=uJ6HPU7Qosk',
    muscleGroups: ['chest', 'arms', 'core'],
    descriptionEN: 'Explosive upper body plyometric exercise.',
    descriptionDE: 'Explosive Oberkörper-Plyometrie-Übung.',
  },

  // SPEED & CONDITIONING
  {
    name: 'Sprint Training',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=VrwnxX5wgqE',
    muscleGroups: ['legs', 'full-body'],
    descriptionEN: 'Maximum velocity running for speed development.',
    descriptionDE: 'Maximales Geschwindigkeitslaufen für Geschwindigkeitsentwicklung.',
  },
  {
    name: 'Hill Sprints',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=CTPYJJGzlem',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Uphill sprinting for power and conditioning.',
    descriptionDE: 'Bergauf-Sprint für Kraft und Konditionierung.',
  },
  {
    name: 'Sled Push',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=rvSzQSP-bd0',
    muscleGroups: ['legs', 'full-body'],
    descriptionEN: 'Weighted sled pushing for strength and conditioning.',
    descriptionDE: 'Gewichteter Schlittenschub für Kraft und Konditionierung.',
  },
  {
    name: 'Sled Pull',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=eQh0Dit-Ul4',
    muscleGroups: ['legs', 'back', 'full-body'],
    descriptionEN: 'Backward sled pulling for posterior chain and conditioning.',
    descriptionDE: 'Rückwärts Schlittenziehen für hintere Kette und Konditionierung.',
  },
  {
    name: 'Prowler Push',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=4M32hZ3ogXk',
    muscleGroups: ['legs', 'full-body'],
    descriptionEN: 'Heavy prowler pushing for power and work capacity.',
    descriptionDE: 'Schweres Prowler-Schieben für Kraft und Arbeitskapazität.',
  },
  {
    name: 'Battle Ropes',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=u0MAvLLmB7A',
    muscleGroups: ['arms', 'shoulders', 'core'],
    descriptionEN: 'Wave exercises with heavy ropes for conditioning.',
    descriptionDE: 'Wellenübungen mit schweren Seilen für Konditionierung.',
  },
  {
    name: 'Rowing Machine',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=zQ82RYIFLN8',
    muscleGroups: ['full-body'],
    descriptionEN: 'Full body cardio machine for endurance.',
    descriptionDE: 'Ganzkörper-Cardio-Gerät für Ausdauer.',
  },
  {
    name: 'Assault Bike',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=5nchdFCF_P8',
    muscleGroups: ['full-body'],
    descriptionEN: 'Air bike for high-intensity interval training.',
    descriptionDE: 'Luftfahrrad für hochintensives Intervalltraining.',
  },
  {
    name: 'Running (Steady State)',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=brFHyOtTwH4',
    muscleGroups: ['legs', 'full-body'],
    descriptionEN: 'Continuous running at moderate pace for aerobic conditioning.',
    descriptionDE: 'Kontinuierliches Laufen in moderatem Tempo für aerobe Konditionierung.',
  },
  {
    name: 'Cycling',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=zy5K8ApSGf4',
    muscleGroups: ['legs'],
    descriptionEN: 'Low-impact cardio exercise on bicycle.',
    descriptionDE: 'Gelenkschonendes Cardio-Training auf dem Fahrrad.',
  },
  {
    name: 'Swimming',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=5HLW2AI1Ink',
    muscleGroups: ['full-body'],
    descriptionEN: 'Full body low-impact cardio in water.',
    descriptionDE: 'Ganzkörper-gelenkschonendes Cardio im Wasser.',
  },

  // CHANGE OF DIRECTION (COD)
  {
    name: 'Pro Agility Drill (5-10-5)',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=jnBDGo0C5Vs',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Standard agility test with direction changes.',
    descriptionDE: 'Standard-Agilitätstest mit Richtungswechseln.',
  },
  {
    name: 'L-Drill (3-Cone Drill)',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=jmw84mfhCLE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Cone drill for agility and change of direction.',
    descriptionDE: 'Hütchenübung für Agilität und Richtungswechsel.',
  },
  {
    name: 'Shuttle Runs',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=TUpCKBjA7X8',
    muscleGroups: ['legs', 'full-body'],
    descriptionEN: 'Back and forth sprinting for agility.',
    descriptionDE: 'Hin- und Hersprint für Agilität.',
  },
  {
    name: 'Lateral Shuffle',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=gj7M9wog4fM',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Side-to-side movement for lateral quickness.',
    descriptionDE: 'Seitwärtsbewegung für seitliche Schnelligkeit.',
  },
  {
    name: 'Carioca Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=mmjQlKXqMBQ',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Crossover running drill for hip mobility and coordination.',
    descriptionDE: 'Überkreuz-Laufübung für Hüftmobilität und Koordination.',
  },

  // MOBILITY & FLEXIBILITY
  {
    name: 'Dynamic Stretching Routine',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=FSSDLDhbacc',
    muscleGroups: ['full-body'],
    descriptionEN: 'Full body dynamic stretches for warm-up.',
    descriptionDE: 'Ganzkörper-dynamisches Dehnen für Aufwärmen.',
  },
  {
    name: 'Leg Swings',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=2aL_5lNZQhY',
    muscleGroups: ['legs'],
    descriptionEN: 'Dynamic hip mobility exercise.',
    descriptionDE: 'Dynamische Hüftmobilitätsübung.',
  },
  {
    name: 'Hip Circles',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=WC4mzWSc_bs',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Hip mobility and activation exercise.',
    descriptionDE: 'Hüftmobilität und Aktivierungsübung.',
  },
  {
    name: 'Foam Rolling',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=vc7HPffJKkw',
    muscleGroups: ['full-body'],
    descriptionEN: 'Self-myofascial release for recovery.',
    descriptionDE: 'Selbst-myofasziale Entspannung für Erholung.',
  },
  {
    name: 'Yoga Flow',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=v7AYKMP6rOE',
    muscleGroups: ['full-body'],
    descriptionEN: 'Flowing yoga sequence for flexibility and mobility.',
    descriptionDE: 'Fließende Yoga-Sequenz für Flexibilität und Mobilität.',
  },
  {
    name: 'Static Stretching',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=g_tea8ZNk5A',
    muscleGroups: ['full-body'],
    descriptionEN: 'Post-workout static stretches for flexibility.',
    descriptionDE: 'Statisches Dehnen nach dem Training für Flexibilität.',
  },

  // CORE
  {
    name: 'Plank',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    muscleGroups: ['core'],
    descriptionEN: 'Isometric core exercise for stability.',
    descriptionDE: 'Isometrische Rumpfübung für Stabilität.',
  },
  {
    name: 'Side Plank',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=K2VljzCC16g',
    muscleGroups: ['core'],
    descriptionEN: 'Lateral core stability exercise.',
    descriptionDE: 'Seitliche Rumpfstabilitätsübung.',
  },
  {
    name: 'Hanging Leg Raises',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
    muscleGroups: ['core', 'arms'],
    descriptionEN: 'Advanced core exercise for lower abs.',
    descriptionDE: 'Fortgeschrittene Rumpfübung für untere Bauchmuskeln.',
  },
  {
    name: 'Russian Twists',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=wkD8rjkodUI',
    muscleGroups: ['core'],
    descriptionEN: 'Rotational core exercise for obliques.',
    descriptionDE: 'Rotationsübung für seitliche Bauchmuskeln.',
  },
  {
    name: 'Ab Wheel Rollout',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=EaByv-aKVQg',
    muscleGroups: ['core', 'arms'],
    descriptionEN: 'Advanced core stability and strength exercise.',
    descriptionDE: 'Fortgeschrittene Rumpfstabilität und Kraftübung.',
  },
  {
    name: 'Cable Woodchops',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=pAplQXk3dkU',
    muscleGroups: ['core', 'shoulders'],
    descriptionEN: 'Rotational power exercise for core.',
    descriptionDE: 'Rotationskraftübung für den Rumpf.',
  },
  {
    name: 'Pallof Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=AH_QZLm_0-s',
    muscleGroups: ['core'],
    descriptionEN: 'Anti-rotation core stability exercise.',
    descriptionDE: 'Anti-Rotations-Rumpfstabilitätsübung.',
  },

  // TECHNIQUE (Football-specific)
  {
    name: 'Sled Blocking Technique',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=X_RThGjk7uA',
    muscleGroups: ['full-body'],
    descriptionEN: 'Football-specific blocking technique with sled.',
    descriptionDE: 'Football-spezifische Blocktechnik mit Schlitten.',
  },
  {
    name: 'Tackling Technique',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=QNDxGDx6X_Y',
    muscleGroups: ['full-body'],
    descriptionEN: 'Proper tackling form and technique.',
    descriptionDE: 'Richtige Tackling-Form und Technik.',
  },
  {
    name: 'Ball Security Drills',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=rPx4YKkr0wg',
    muscleGroups: ['arms', 'core'],
    descriptionEN: 'Ball carrying and protection techniques.',
    descriptionDE: 'Balltrage- und Schutztechniken.',
  },
  {
    name: 'Footwork Ladder Drills',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=f5_NvcCL5s4',
    muscleGroups: ['legs'],
    descriptionEN: 'Agility ladder for footwork and coordination.',
    descriptionDE: 'Koordinationsleiter für Fußarbeit und Koordination.',
  },

  // ADDITIONAL STRENGTH - More Variations
  {
    name: 'Goblet Squat',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=MeHQ_4O55jI',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Dumbbell front-loaded squat variation, great for beginners.',
    descriptionDE: 'Kurzhantel-frontal-Kniebeuge-Variante, ideal für Anfänger.',
  },
  {
    name: 'Hack Squat',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=0tn5K9NlCfo',
    muscleGroups: ['legs'],
    descriptionEN: 'Machine squat variation targeting quads.',
    descriptionDE: 'Maschinen-Kniebeuge-Variante für Quadrizeps.',
  },
  {
    name: 'Sumo Deadlift',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=NxRx62v6Txc',
    muscleGroups: ['legs', 'back'],
    descriptionEN: 'Wide-stance deadlift variation emphasizing inner thighs.',
    descriptionDE: 'Breite Kreuzheben-Variante mit Betonung auf Oberschenkelinnenseiten.',
  },
  {
    name: 'Trap Bar Deadlift',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=WlkMX1aLbws',
    muscleGroups: ['legs', 'back', 'core'],
    descriptionEN: 'Hex bar deadlift, easier on lower back.',
    descriptionDE: 'Hex-Bar-Kreuzheben, schonender für unteren Rücken.',
  },
  {
    name: 'Good Mornings',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=YA-h3n9L4YU',
    muscleGroups: ['legs', 'back'],
    descriptionEN: 'Hip hinge exercise for posterior chain.',
    descriptionDE: 'Hüftbeuge-Übung für hintere Muskelkette.',
  },
  {
    name: 'Dumbbell Flyes',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=eozdVDA78K0',
    muscleGroups: ['chest'],
    descriptionEN: 'Chest isolation exercise with dumbbells.',
    descriptionDE: 'Brust-Isolationsübung mit Kurzhanteln.',
  },
  {
    name: 'Cable Crossover',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=taI4XduLpTk',
    muscleGroups: ['chest'],
    descriptionEN: 'Cable chest fly for constant tension.',
    descriptionDE: 'Kabel-Brustfliegen für konstante Spannung.',
  },
  {
    name: 'Decline Bench Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=LfyQBUKR8SE',
    muscleGroups: ['chest', 'arms'],
    descriptionEN: 'Targets lower chest with decline angle.',
    descriptionDE: 'Zielt auf untere Brust mit Neigungswinkel.',
  },
  {
    name: 'Dumbbell Pullover',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=FK4A6BZSkBM',
    muscleGroups: ['chest', 'back'],
    descriptionEN: 'Chest and lat exercise with dumbbell.',
    descriptionDE: 'Brust- und Latübung mit Kurzhantel.',
  },
  {
    name: 'T-Bar Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=j3Igk5nyZE4',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Rowing variation for thick back development.',
    descriptionDE: 'Ruder-Variante für dicke Rückenentwicklung.',
  },
  {
    name: 'Pendlay Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=iYRPQ1j8pPY',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Explosive barbell row from floor.',
    descriptionDE: 'Explosives Langhantelrudern vom Boden.',
  },
  {
    name: 'Seal Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=akOQKGDqO14',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Supported row eliminating lower back stress.',
    descriptionDE: 'Gestütztes Rudern ohne Belastung des unteren Rückens.',
  },
  {
    name: 'Meadows Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=RQfZpygSLbY',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Single-arm landmine row for back thickness.',
    descriptionDE: 'Einarm-Landminen-Rudern für Rückendicke.',
  },
  {
    name: 'Chest Supported Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=iXnKsc-TXCc',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Machine or bench-supported rowing.',
    descriptionDE: 'Maschinen- oder bankgestütztes Rudern.',
  },
  {
    name: 'Inverted Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=hXTc1mDnZCw',
    muscleGroups: ['back', 'arms'],
    descriptionEN: 'Bodyweight horizontal pull exercise.',
    descriptionDE: 'Körpergewichts-horizontale Zugübung.',
  },
  {
    name: 'Arnold Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=6Z15_WdXmVw',
    muscleGroups: ['shoulders', 'arms'],
    descriptionEN: 'Rotating dumbbell shoulder press.',
    descriptionDE: 'Rotierende Kurzhantel-Schulterdrücken.',
  },
  {
    name: 'Lateral Raises',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    muscleGroups: ['shoulders'],
    descriptionEN: 'Side delt isolation with dumbbells.',
    descriptionDE: 'Seitliche Schulter-Isolation mit Kurzhanteln.',
  },
  {
    name: 'Front Raises',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=dDEd_fLlYH8',
    muscleGroups: ['shoulders'],
    descriptionEN: 'Front delt isolation exercise.',
    descriptionDE: 'Vordere Schulter-Isolationsübung.',
  },
  {
    name: 'Rear Delt Flyes',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=ttvfGg9d76c',
    muscleGroups: ['shoulders'],
    descriptionEN: 'Rear shoulder isolation with dumbbells.',
    descriptionDE: 'Hintere Schulter-Isolation mit Kurzhanteln.',
  },
  {
    name: 'Upright Row',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=5b4tVoETlL0',
    muscleGroups: ['shoulders', 'arms'],
    descriptionEN: 'Vertical pull for shoulders and traps.',
    descriptionDE: 'Vertikaler Zug für Schultern und Trapez.',
  },
  {
    name: 'Shrugs',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=cJRVVxmytaM',
    muscleGroups: ['shoulders', 'back'],
    descriptionEN: 'Trap-focused shoulder shrug.',
    descriptionDE: 'Trapez-fokussiertes Schulterzucken.',
  },
  {
    name: 'Hammer Curls',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    muscleGroups: ['arms'],
    descriptionEN: 'Neutral grip bicep curl variation.',
    descriptionDE: 'Neutrale Griff-Bizeps-Curl-Variante.',
  },
  {
    name: 'Preacher Curls',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=fIWP-FRFNU0',
    muscleGroups: ['arms'],
    descriptionEN: 'Bicep isolation on preacher bench.',
    descriptionDE: 'Bizeps-Isolation auf Schrägbank.',
  },
  {
    name: 'Concentration Curls',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=Jvj6wbLHLKQ',
    muscleGroups: ['arms'],
    descriptionEN: 'Seated single-arm bicep curl.',
    descriptionDE: 'Sitzende Einarm-Bizeps-Curl.',
  },
  {
    name: 'Tricep Pushdown',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=-xa-6cQaZKY',
    muscleGroups: ['arms'],
    descriptionEN: 'Cable tricep extension exercise.',
    descriptionDE: 'Kabel-Trizeps-Streckungsübung.',
  },
  {
    name: 'Overhead Tricep Extension',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q',
    muscleGroups: ['arms'],
    descriptionEN: 'Overhead dumbbell tricep exercise.',
    descriptionDE: 'Überkopf-Kurzhantel-Trizepsübung.',
  },
  {
    name: 'Close-Grip Bench Press',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=nEF0bv2FW94',
    muscleGroups: ['arms', 'chest'],
    descriptionEN: 'Narrow grip bench for triceps.',
    descriptionDE: 'Enggriff-Bankdrücken für Trizeps.',
  },
  {
    name: 'Diamond Push-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=J0DnG1_S92I',
    muscleGroups: ['arms', 'chest'],
    descriptionEN: 'Close-grip push-up for triceps.',
    descriptionDE: 'Enggriff-Liegestütze für Trizeps.',
  },

  // MORE LEGS
  {
    name: 'Nordic Curls',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=CxBtWFMEBtQ',
    muscleGroups: ['legs'],
    descriptionEN: 'Eccentric hamstring exercise.',
    descriptionDE: 'Exzentrische Oberschenkelrückseiten-Übung.',
  },
  {
    name: 'Glute Ham Raise',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=kJUmGxfjQ3A',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Hamstring and glute developer exercise.',
    descriptionDE: 'Oberschenkelrückseiten- und Gesäßentwicklungsübung.',
  },
  {
    name: 'Walking Lunges',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=L8fvypPrzzs',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Dynamic lunge variation moving forward.',
    descriptionDE: 'Dynamische Ausfallschritte vorwärts.',
  },
  {
    name: 'Reverse Lunges',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=xXj4P_YyFp8',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Backward stepping lunge, easier on knees.',
    descriptionDE: 'Rückwärts-Ausfallschritt, schonender für Knie.',
  },
  {
    name: 'Step-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQqApCGd5Ss',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Stepping onto elevated platform.',
    descriptionDE: 'Auf erhöhte Plattform steigen.',
  },
  {
    name: 'Pistol Squats',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=qDcniqddTeE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Single-leg bodyweight squat.',
    descriptionDE: 'Einbein-Körpergewicht-Kniebeuge.',
  },
  {
    name: 'Calf Raises',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=gwLzBJYoWlI',
    muscleGroups: ['legs'],
    descriptionEN: 'Standing calf exercise for lower leg.',
    descriptionDE: 'Stehende Wadenübung für Unterschenkel.',
  },
  {
    name: 'Seated Calf Raises',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=JbyjNymZOt0',
    muscleGroups: ['legs'],
    descriptionEN: 'Seated variation targeting soleus.',
    descriptionDE: 'Sitzende Variante für Schollenmuskel.',
  },

  // BODYWEIGHT & FUNCTIONAL
  {
    name: 'Push-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    muscleGroups: ['chest', 'arms', 'core'],
    descriptionEN: 'Classic bodyweight pushing exercise.',
    descriptionDE: 'Klassische Körpergewichts-Drückübung.',
  },
  {
    name: 'Wide-Grip Push-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=ZpTHIz0_JPU',
    muscleGroups: ['chest', 'arms'],
    descriptionEN: 'Wide hand position emphasizing chest.',
    descriptionDE: 'Breite Handposition mit Betonung auf Brust.',
  },
  {
    name: 'Decline Push-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=SKPab2YC8BE',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    descriptionEN: 'Feet elevated push-up variation.',
    descriptionDE: 'Liegestütze mit erhöhten Füßen.',
  },
  {
    name: 'Pike Push-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=x3_XJNKMrDc',
    muscleGroups: ['shoulders', 'arms'],
    descriptionEN: 'Angled push-up for shoulders.',
    descriptionDE: 'Abgewinkelte Liegestütze für Schultern.',
  },
  {
    name: 'Burpees',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=dZgVxmf6jkA',
    muscleGroups: ['full-body'],
    descriptionEN: 'Full body conditioning exercise.',
    descriptionDE: 'Ganzkörper-Konditionierungsübung.',
  },
  {
    name: 'Mountain Climbers',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    muscleGroups: ['core', 'legs'],
    descriptionEN: 'Dynamic core and cardio exercise.',
    descriptionDE: 'Dynamische Rumpf- und Cardio-Übung.',
  },
  {
    name: 'Jumping Jacks',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=iSSAk4EHpvQ',
    muscleGroups: ['full-body'],
    descriptionEN: 'Classic warm-up and cardio exercise.',
    descriptionDE: 'Klassische Aufwärm- und Cardio-Übung.',
  },
  {
    name: 'High Knees',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=8opcQdC-V-U',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Running in place with high knee drive.',
    descriptionDE: 'Laufen auf der Stelle mit hohem Kniehub.',
  },
  {
    name: 'Butt Kicks',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=8qO4HJJdcnk',
    muscleGroups: ['legs'],
    descriptionEN: 'Running in place kicking heels to glutes.',
    descriptionDE: 'Laufen auf der Stelle mit Fersen zum Gesäß.',
  },

  // OLYMPIC LIFTS & POWER
  {
    name: 'Power Clean',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=KwYJTpQ_x5A',
    muscleGroups: ['full-body'],
    descriptionEN: 'Explosive Olympic lift for total body power.',
    descriptionDE: 'Explosives olympisches Heben für Ganzkörperkraft.',
  },
  {
    name: 'Hang Clean',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=0aP3tgKZcHQ',
    muscleGroups: ['full-body'],
    descriptionEN: 'Power clean from hang position.',
    descriptionDE: 'Power Clean aus hängender Position.',
  },
  {
    name: 'Clean and Jerk',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=PjY1rH4_MOA',
    muscleGroups: ['full-body'],
    descriptionEN: 'Full Olympic lift with overhead press.',
    descriptionDE: 'Vollständiges olympisches Heben mit Überkopfdrücken.',
  },
  {
    name: 'Snatch',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=9xQp2sldyts',
    muscleGroups: ['full-body'],
    descriptionEN: 'Single-motion Olympic lift overhead.',
    descriptionDE: 'Einbewegung olympisches Heben überkopf.',
  },
  {
    name: 'Push Press',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=iaBVSJm78ko',
    muscleGroups: ['shoulders', 'legs'],
    descriptionEN: 'Explosive overhead press with leg drive.',
    descriptionDE: 'Explosives Überkopfdrücken mit Beinantrieb.',
  },
  {
    name: 'Push Jerk',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=8pLCNQMiR_U',
    muscleGroups: ['shoulders', 'legs'],
    descriptionEN: 'Explosive jerk with dip under bar.',
    descriptionDE: 'Explosives Stoßen mit Abtauchen unter die Stange.',
  },
  {
    name: 'Kettlebell Swing',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=YSxHifyI6s8',
    muscleGroups: ['legs', 'back', 'core'],
    descriptionEN: 'Hip hinge power exercise with kettlebell.',
    descriptionDE: 'Hüftbeuge-Kraftübung mit Kettlebell.',
  },
  {
    name: 'Kettlebell Snatch',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=XBKRPS_MkIg',
    muscleGroups: ['full-body'],
    descriptionEN: 'Explosive kettlebell overhead movement.',
    descriptionDE: 'Explosive Kettlebell-Überkopf-Bewegung.',
  },
  {
    name: 'Kettlebell Clean',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=rmLdSGfxpRU',
    muscleGroups: ['full-body'],
    descriptionEN: 'Kettlebell clean to rack position.',
    descriptionDE: 'Kettlebell Clean zur Rack-Position.',
  },
  {
    name: 'Turkish Get-up',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=d8B_1FcbZy4',
    muscleGroups: ['full-body', 'core'],
    descriptionEN: 'Complex full-body movement with kettlebell.',
    descriptionDE: 'Komplexe Ganzkörper-Bewegung mit Kettlebell.',
  },

  // STRETCHING & WARM-UP
  {
    name: 'Arm Circles',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=KJNUu7JxqUk',
    muscleGroups: ['shoulders'],
    descriptionEN: 'Dynamic shoulder warm-up exercise.',
    descriptionDE: 'Dynamische Schulter-Aufwärmübung.',
  },
  {
    name: 'World\'s Greatest Stretch',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=0GSe6D9T3rM',
    muscleGroups: ['full-body'],
    descriptionEN: 'Comprehensive full-body dynamic stretch.',
    descriptionDE: 'Umfassende Ganzkörper-dynamische Dehnung.',
  },
  {
    name: 'Inchworms',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=vc1E5CfRfos',
    muscleGroups: ['full-body', 'core'],
    descriptionEN: 'Walking hands out to plank and back.',
    descriptionDE: 'Mit Händen zur Planke laufen und zurück.',
  },
  {
    name: 'Spiderman Stretch',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=eCGvdTpFXMc',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Hip mobility and hamstring stretch.',
    descriptionDE: 'Hüftmobilität und Oberschenkelrückseiten-Dehnung.',
  },
  {
    name: 'Cat-Cow Stretch',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=kqnua4rHVVA',
    muscleGroups: ['back', 'core'],
    descriptionEN: 'Spinal mobility exercise.',
    descriptionDE: 'Wirbelsäulen-Mobilitätsübung.',
  },
  {
    name: 'Scorpion Stretch',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=7wI55MFZoU4',
    muscleGroups: ['back', 'core'],
    descriptionEN: 'Thoracic spine rotation stretch.',
    descriptionDE: 'Brustwirbelsäulen-Rotationsdehnung.',
  },
  {
    name: 'Downward Dog',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=9S3nN1V-C6o',
    muscleGroups: ['full-body'],
    descriptionEN: 'Yoga pose for hamstrings and shoulders.',
    descriptionDE: 'Yoga-Haltung für Oberschenkelrückseiten und Schultern.',
  },
  {
    name: 'Pigeon Pose',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=0_zPqA65Nok',
    muscleGroups: ['legs'],
    descriptionEN: 'Deep hip and glute stretch.',
    descriptionDE: 'Tiefe Hüft- und Gesäßdehnung.',
  },

  // CORE VARIATIONS
  {
    name: 'Bicycle Crunches',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=1we3bh9uhqY',
    muscleGroups: ['core'],
    descriptionEN: 'Rotating crunch for obliques.',
    descriptionDE: 'Rotierende Crunches für seitliche Bauchmuskeln.',
  },
  {
    name: 'V-ups',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=iP3blw1HAhI',
    muscleGroups: ['core'],
    descriptionEN: 'Advanced full sit-up to pike position.',
    descriptionDE: 'Fortgeschrittener vollständiger Sit-up zur Pike-Position.',
  },
  {
    name: 'Dead Bug',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=g_BYB0R-4Ws',
    muscleGroups: ['core'],
    descriptionEN: 'Core stability exercise on back.',
    descriptionDE: 'Rumpfstabilitätsübung auf dem Rücken.',
  },
  {
    name: 'Bird Dog',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=wiFNA3sqjCA',
    muscleGroups: ['core', 'back'],
    descriptionEN: 'Opposite arm and leg extension for stability.',
    descriptionDE: 'Gegenüberliegende Arm- und Beinstreckung für Stabilität.',
  },
  {
    name: 'Hollow Body Hold',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=LlDNef_Ztsc',
    muscleGroups: ['core'],
    descriptionEN: 'Gymnastic core hold position.',
    descriptionDE: 'Gymnastik-Rumpfhalteposition.',
  },
  {
    name: 'Dragon Flag',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=njKXkuhY7_0',
    muscleGroups: ['core'],
    descriptionEN: 'Advanced core exercise made famous by Bruce Lee.',
    descriptionDE: 'Fortgeschrittene Rumpfübung, berühmt gemacht durch Bruce Lee.',
  },
  {
    name: 'Windshield Wipers',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=ObiZO4cXKTw',
    muscleGroups: ['core'],
    descriptionEN: 'Hanging oblique rotation exercise.',
    descriptionDE: 'Hängende seitliche Rotationsübung.',
  },
  {
    name: 'L-Sit',
    category: 'Strength',
    youtubeUrl: 'https://www.youtube.com/watch?v=IUZJrTCR5xo',
    muscleGroups: ['core', 'arms'],
    descriptionEN: 'Isometric core and hip flexor hold.',
    descriptionDE: 'Isometrische Rumpf- und Hüftbeuger-Halteposition.',
  },

  // ========================================
  // SPEED TRAINING - American Football
  // ========================================
  {
    name: '40-Yard Dash',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=nffjpN1YPL4',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Classic 40-yard sprint test for football speed.',
    descriptionDE: 'Klassischer 40-Yard-Sprint-Test für Football-Geschwindigkeit.',
  },
  {
    name: '10-Yard Sprint',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=AiNJwVT2Ujo',
    muscleGroups: ['legs'],
    descriptionEN: 'Short burst acceleration sprint.',
    descriptionDE: 'Kurzer explosiver Beschleunigungssprint.',
  },
  {
    name: '20-Yard Shuttle',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=wCF8sKBOUTE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: '5-10-5 shuttle drill for speed and agility.',
    descriptionDE: '5-10-5 Shuttle-Drill für Geschwindigkeit und Agilität.',
  },
  {
    name: 'Flying 30s',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=MWQYpuGK0fc',
    muscleGroups: ['legs'],
    descriptionEN: 'Build-up sprint with 30-yard max velocity zone.',
    descriptionDE: 'Anlauf-Sprint mit 30-Yard-Maximalgeschwindigkeitszone.',
  },
  {
    name: 'Hill Sprints',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=6XLc1LGtm-Q',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Uphill sprints for explosive power and speed.',
    descriptionDE: 'Bergauf-Sprints für explosive Kraft und Geschwindigkeit.',
  },
  {
    name: 'Resisted Sprints (Sled)',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=sP_4vyT6jj4',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Weighted sled sprint for acceleration strength.',
    descriptionDE: 'Gewichteter Schlitten-Sprint für Beschleunigungskraft.',
  },
  {
    name: 'Parachute Sprints',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=nN1Kzz6b2O8',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Resistance sprint training with parachute.',
    descriptionDE: 'Widerstands-Sprint-Training mit Fallschirm.',
  },
  {
    name: 'Band Assisted Sprints',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=lhK2F2zDaAI',
    muscleGroups: ['legs'],
    descriptionEN: 'Overspeed training with resistance bands.',
    descriptionDE: 'Überschnelligkeitstraining mit Widerstandsbändern.',
  },
  {
    name: 'A-Skips',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=E7_9c7Ufe0Y',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Technical sprint drill for knee drive and posture.',
    descriptionDE: 'Technischer Sprint-Drill für Kniehub und Haltung.',
  },
  {
    name: 'B-Skips',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=eYhyjd0Fm2M',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Advanced sprint mechanics drill with leg extension.',
    descriptionDE: 'Fortgeschrittener Sprint-Mechanik-Drill mit Beinstreckung.',
  },
  {
    name: 'C-Skips',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=N-_rvq-wftg',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Sprint drill emphasizing circular leg action.',
    descriptionDE: 'Sprint-Drill mit Betonung auf zirkuläre Beinbewegung.',
  },
  {
    name: 'Wall Drill',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=lbonoR24Z1M',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Sprint posture and mechanics drill against wall.',
    descriptionDE: 'Sprint-Haltungs- und Mechanik-Drill an der Wand.',
  },
  {
    name: 'Wicket Run-throughs',
    category: 'Speed',
    youtubeUrl: 'https://www.youtube.com/watch?v=GK5TZ7cchJk',
    muscleGroups: ['legs'],
    descriptionEN: 'Sprint stride length and frequency training.',
    descriptionDE: 'Sprint-Schrittlängen- und Frequenztraining.',
  },

  // ========================================
  // COD (CHANGE OF DIRECTION) - Football Agility
  // ========================================
  {
    name: '3-Cone Drill (L-Drill)',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=2w7UJKwHOr8',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Classic NFL Combine agility drill.',
    descriptionDE: 'Klassischer NFL Combine Agilitäts-Drill.',
  },
  {
    name: 'Pro Agility (5-10-5)',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=wCF8sKBOUTE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Lateral change of direction shuttle.',
    descriptionDE: 'Lateraler Richtungswechsel-Shuttle.',
  },
  {
    name: 'W-Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=yXGfR3KeOYM',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Multi-directional agility pattern drill.',
    descriptionDE: 'Multi-direktionaler Agilitätsmuster-Drill.',
  },
  {
    name: 'Star Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=KoY8EXfHGlo',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Explosive multi-angle acceleration drill.',
    descriptionDE: 'Explosiver Multi-Winkel-Beschleunigungs-Drill.',
  },
  {
    name: 'T-Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=IdBNKBDN5Jw',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Forward, lateral, and backpedal agility.',
    descriptionDE: 'Vorwärts-, Lateral- und Rückwärts-Agilität.',
  },
  {
    name: 'Z-Pattern Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=vJ2u6Lbjs0o',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Diagonal cutting and acceleration pattern.',
    descriptionDE: 'Diagonales Schnitt- und Beschleunigungsmuster.',
  },
  {
    name: 'Box Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=m4kEEBa1_jk',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Square agility pattern with 90-degree cuts.',
    descriptionDE: 'Quadrat-Agilitätsmuster mit 90-Grad-Schnitten.',
  },
  {
    name: 'Hexagon Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=jlqiP3P1HCA',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Six-direction jump and turn drill.',
    descriptionDE: 'Sechs-Richtungs-Sprung- und Drehübung.',
  },
  {
    name: 'Mirror Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=gXSKfq1xXV4',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Reactive lateral movement training.',
    descriptionDE: 'Reaktives laterales Bewegungstraining.',
  },
  {
    name: 'Reactive Cone Drill',
    category: 'COD',
    youtubeUrl: 'https://www.youtube.com/watch?v=8PwoytUU06g',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Random direction response drill.',
    descriptionDE: 'Zufällige Richtungsreaktions-Drill.',
  },

  // ========================================
  // PLYOMETRICS - Explosive Power
  // ========================================
  {
    name: 'Box Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=52r_Ul5k03g',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Explosive vertical jump onto elevated platform.',
    descriptionDE: 'Explosiver vertikaler Sprung auf erhöhte Plattform.',
  },
  {
    name: 'Depth Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=JXKj094xqwQ',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Drop from box and explosive rebound jump.',
    descriptionDE: 'Fall von Box und explosiver Rückprall-Sprung.',
  },
  {
    name: 'Broad Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=WzLCfFPUHQc',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Horizontal explosive long jump.',
    descriptionDE: 'Horizontaler explosiver Weitsprung.',
  },
  {
    name: 'Lateral Bounds',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=BvLw9NmHrJg',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Side-to-side explosive single-leg hops.',
    descriptionDE: 'Seitliche explosive Einbein-Hüpfer.',
  },
  {
    name: 'Single-Leg Box Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=tq-w5UYxGiE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Unilateral explosive jump training.',
    descriptionDE: 'Einseitiges explosives Sprungtraining.',
  },
  {
    name: 'Hurdle Hops',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=PNZwfJJb6hE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Consecutive hurdle jumps for reactive strength.',
    descriptionDE: 'Aufeinanderfolgende Hürdensprünge für reaktive Kraft.',
  },
  {
    name: 'Tuck Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=gfTtBSywH7M',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Maximum vertical jump with knee tuck.',
    descriptionDE: 'Maximaler vertikaler Sprung mit Knie-Tuck.',
  },
  {
    name: 'Split Jumps',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=W5bqb3E3-0c',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Alternating lunge jumps for explosiveness.',
    descriptionDE: 'Wechselnde Ausfallschritt-Sprünge für Explosivität.',
  },
  {
    name: 'Medicine Ball Slams',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=oHFGs3QPY9I',
    muscleGroups: ['full-body', 'core'],
    descriptionEN: 'Overhead medicine ball slam for power.',
    descriptionDE: 'Überkopf-Medizinball-Schlag für Kraft.',
  },
  {
    name: 'Medicine Ball Chest Pass',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=jJP4GjJX-30',
    muscleGroups: ['chest', 'arms', 'core'],
    descriptionEN: 'Explosive chest throw with medicine ball.',
    descriptionDE: 'Explosiver Brustwurf mit Medizinball.',
  },
  {
    name: 'Medicine Ball Overhead Throw',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=uPIB_KhFQcg',
    muscleGroups: ['full-body', 'core'],
    descriptionEN: 'Overhead backward medicine ball throw.',
    descriptionDE: 'Überkopf-Rückwärts-Medizinball-Wurf.',
  },
  {
    name: 'Clap Push-ups',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=vuEz_TRE8S0',
    muscleGroups: ['chest', 'arms', 'core'],
    descriptionEN: 'Explosive push-up with hand clap.',
    descriptionDE: 'Explosiver Liegestütz mit Händeklatschen.',
  },
  {
    name: 'Plyo Push-ups',
    category: 'Plyometrics',
    youtubeUrl: 'https://www.youtube.com/watch?v=5nBv6SQ8S5g',
    muscleGroups: ['chest', 'arms', 'core'],
    descriptionEN: 'Plyometric push-up variations.',
    descriptionDE: 'Plyometrische Liegestütz-Varianten.',
  },

  // ========================================
  // MOBILITY & FLEXIBILITY - Football Specific
  // ========================================
  {
    name: 'Hip Flexor Stretch',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=ZyFXN_u_0bA',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Kneeling hip flexor and quad stretch.',
    descriptionDE: 'Kniende Hüftbeuger- und Quad-Dehnung.',
  },
  {
    name: '90/90 Hip Stretch',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=XkGPbXnW6Es',
    muscleGroups: ['legs'],
    descriptionEN: 'Seated hip internal and external rotation.',
    descriptionDE: 'Sitzende Hüft-Innen- und Außenrotation.',
  },
  {
    name: 'Cossack Squat',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=tpczTeSkHz0',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Lateral squat for hip and adductor mobility.',
    descriptionDE: 'Laterale Kniebeuge für Hüft- und Adduktoren-Mobilität.',
  },
  {
    name: 'Deep Squat Hold',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=9I5x8QQHcXE',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Bottom squat position hold for ankle and hip mobility.',
    descriptionDE: 'Untere Kniebeuge-Position halten für Knöchel- und Hüftmobilität.',
  },
  {
    name: 'Thoracic Spine Rotations',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=7hPPLUYdLnk',
    muscleGroups: ['back', 'core'],
    descriptionEN: 'Upper back rotation for throwing mechanics.',
    descriptionDE: 'Oberer Rücken-Rotation für Wurfmechanik.',
  },
  {
    name: 'Shoulder Dislocations',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=33P5AI27eiU',
    muscleGroups: ['shoulders', 'back'],
    descriptionEN: 'Band or stick shoulder mobility drill.',
    descriptionDE: 'Band- oder Stab-Schultermobilitäts-Drill.',
  },
  {
    name: 'Ankle Mobility Drill',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=P4N6T1hjbKE',
    muscleGroups: ['legs'],
    descriptionEN: 'Dorsiflexion and ankle flexibility work.',
    descriptionDE: 'Dorsalflexion und Knöchelflexibilitätsarbeit.',
  },
  {
    name: 'Frog Stretch',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=tRQ5ly-QlU4',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Deep hip adductor and groin stretch.',
    descriptionDE: 'Tiefe Hüftadduktoren- und Leistendehnung.',
  },
  {
    name: 'Brettzels',
    category: 'Mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=xdkSK_mG2kk',
    muscleGroups: ['back', 'legs', 'core'],
    descriptionEN: 'Full-body rotation and hip mobility stretch.',
    descriptionDE: 'Ganzkörper-Rotations- und Hüftmobilitäts-Dehnung.',
  },

  // ========================================
  // TECHNIQUE - Football Skills
  // ========================================
  {
    name: 'Stance and Start Drill',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=cDL26UgJh6I',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Proper 3-point or 4-point stance technique.',
    descriptionDE: 'Richtige 3-Punkt- oder 4-Punkt-Startposition-Technik.',
  },
  {
    name: 'Backpedal Technique',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=OExjV0rXH3s',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Defensive back backpedal mechanics.',
    descriptionDE: 'Defensive Back Rückwärtslauf-Mechanik.',
  },
  {
    name: 'Hip Turn Drill',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=kbT48SQwQ1M',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'DB technique for transitioning from backpedal.',
    descriptionDE: 'DB-Technik für Übergang vom Rückwärtslauf.',
  },
  {
    name: 'Shed and Tackle Drill',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=lMqKxEwlL8Q',
    muscleGroups: ['full-body'],
    descriptionEN: 'Block shedding and tackling technique.',
    descriptionDE: 'Block-Abwehr- und Tackle-Technik.',
  },
  {
    name: 'Route Running Cuts',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=SXJ-0M8pSRo',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'WR/TE route cutting technique at various angles.',
    descriptionDE: 'WR/TE-Routen-Schnitt-Technik in verschiedenen Winkeln.',
  },
  {
    name: 'Pass Rush Moves',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=x3zfMfq-LiU',
    muscleGroups: ['full-body'],
    descriptionEN: 'DL pass rush technique and hand placement.',
    descriptionDE: 'DL Pass-Rush-Technik und Handplatzierung.',
  },
  {
    name: 'Footwork Gauntlet',
    category: 'Technique',
    youtubeUrl: 'https://www.youtube.com/watch?v=P88j7pLDQYg',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Quick feet and balance through obstacles.',
    descriptionDE: 'Schnelle Füße und Balance durch Hindernisse.',
  },

  // ========================================
  // CONDITIONING - Football Endurance
  // ========================================
  {
    name: 'Gassers',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=vN-HUJlJ0xo',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Sideline-to-sideline conditioning runs.',
    descriptionDE: 'Seitenlinien-zu-Seitenlinien-Konditionierungsläufe.',
  },
  {
    name: '100-Yard Sprint Repeats',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=tRb1ZNQgKHg',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Full-field sprint conditioning.',
    descriptionDE: 'Vollfeld-Sprint-Konditionierung.',
  },
  {
    name: 'Tempo Runs',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=0wBg8DJJsGk',
    muscleGroups: ['legs', 'core'],
    descriptionEN: 'Sub-maximal runs for aerobic conditioning.',
    descriptionDE: 'Sub-maximale Läufe für aerobe Konditionierung.',
  },
  {
    name: 'Prowler Pushes',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=8R-p-mNW1fE',
    muscleGroups: ['legs', 'core', 'full-body'],
    descriptionEN: 'Weighted sled push for strength endurance.',
    descriptionDE: 'Gewichteter Schlitten-Stoß für Kraft-Ausdauer.',
  },
  {
    name: 'Battle Ropes',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=U0RM02YgBWA',
    muscleGroups: ['arms', 'shoulders', 'core'],
    descriptionEN: 'High-intensity upper body conditioning.',
    descriptionDE: 'Hochintensives Oberkörper-Konditionierung.',
  },
  {
    name: 'Assault Bike Sprints',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=WKCBhCPJNlg',
    muscleGroups: ['full-body'],
    descriptionEN: 'HIIT bike intervals for conditioning.',
    descriptionDE: 'HIIT-Fahrrad-Intervalle für Konditionierung.',
  },
  {
    name: 'Rowing Intervals',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=PSCpkkDJJZQ',
    muscleGroups: ['full-body', 'back'],
    descriptionEN: 'Rowing machine HIIT conditioning.',
    descriptionDE: 'Rudergerät HIIT-Konditionierung.',
  },
  {
    name: 'Tire Flips',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=8aLCJIgglbI',
    muscleGroups: ['full-body', 'legs', 'back'],
    descriptionEN: 'Heavy tire flipping for strength and conditioning.',
    descriptionDE: 'Schweres Reifen-Umdrehen für Kraft und Konditionierung.',
  },
  {
    name: 'Farmer Walks',
    category: 'Conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=rt17lmnaLSM',
    muscleGroups: ['full-body', 'core'],
    descriptionEN: 'Heavy loaded carry for grip and core strength.',
    descriptionDE: 'Schwer beladenes Tragen für Griff- und Rumpfkraft.',
  },

  // ========================================
  // RECOVERY - Active Recovery
  // ========================================
  {
    name: 'Foam Rolling - Lower Body',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=1ANP3uRsl1M',
    muscleGroups: ['legs'],
    descriptionEN: 'Self-myofascial release for legs and hips.',
    descriptionDE: 'Selbstmyofasziale Entspannung für Beine und Hüften.',
  },
  {
    name: 'Foam Rolling - Upper Body',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=9kDeVcdJVpw',
    muscleGroups: ['back', 'shoulders'],
    descriptionEN: 'Upper back and shoulder foam rolling.',
    descriptionDE: 'Oberer Rücken und Schulter-Schaumstoffrollen.',
  },
  {
    name: 'Static Hamstring Stretch',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=UB_CURsRHwc',
    muscleGroups: ['legs'],
    descriptionEN: 'Post-workout hamstring flexibility.',
    descriptionDE: 'Post-Workout Oberschenkelrückseiten-Flexibilität.',
  },
  {
    name: 'Quad Stretch',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=P6-yQXHp0r0',
    muscleGroups: ['legs'],
    descriptionEN: 'Standing or lying quadriceps stretch.',
    descriptionDE: 'Stehende oder liegende Quadrizeps-Dehnung.',
  },
  {
    name: 'Child\'s Pose',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=2MN1NSGwN90',
    muscleGroups: ['back', 'core'],
    descriptionEN: 'Restorative yoga pose for back and hips.',
    descriptionDE: 'Erholsame Yoga-Haltung für Rücken und Hüften.',
  },
  {
    name: 'Legs Up the Wall',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=Cy_YvvLlnLE',
    muscleGroups: ['legs'],
    descriptionEN: 'Passive leg drainage and recovery position.',
    descriptionDE: 'Passive Beinentwässerung und Erholungsposition.',
  },
  {
    name: 'Cobra Stretch',
    category: 'Recovery',
    youtubeUrl: 'https://www.youtube.com/watch?v=JDcdhTuycOI',
    muscleGroups: ['back', 'core'],
    descriptionEN: 'Spinal extension and ab stretch.',
    descriptionDE: 'Wirbelsäulenstreckung und Bauch-Dehnung.',
  },
];

async function seedExercises() {
  console.log('[SEED] Starting exercises seed...');

  try {
    // Find the first coach user to assign as creator
    const coach = await prisma.user.findFirst({
      where: { role: 'coach' },
    });

    if (!coach) {
      console.error('[SEED ERROR] No coach found in database. Please create a coach user first.');
      return;
    }

    console.log(`[SEED] Using coach ${coach.email} as creator`);

    let created = 0;
    let updated = 0;

    for (const exercise of standardExercises) {
      const existing = await prisma.exercise.findUnique({
        where: { name: exercise.name },
      });

      if (existing) {
        // FORCE update all existing exercises with muscle groups
        await prisma.exercise.update({
          where: { id: existing.id },
          data: {
            muscleGroups: exercise.muscleGroups,
            descriptionEN: exercise.descriptionEN,
            descriptionDE: exercise.descriptionDE,
            youtubeUrl: exercise.youtubeUrl || existing.youtubeUrl,
          },
        });
        updated++;
        console.log(`[SEED] ↻ Updated: ${exercise.name} (added muscle groups: ${exercise.muscleGroups.join(', ')})`);
        continue;
      }

      await prisma.exercise.create({
        data: {
          ...exercise,
          createdBy: coach.id,
          isGlobal: true,
          isCustom: false,
          positionTags: [], // Empty = available for all positions
        },
      });

      created++;
      console.log(`[SEED] ✓ Created: ${exercise.name} (${exercise.category})`);
    }

    console.log(`\n[SEED] ✅ Exercises seed completed!`);
    console.log(`[SEED] Created: ${created} exercises`);
    console.log(`[SEED] Updated: ${updated} exercises (added muscle groups)`);
    console.log(`[SEED] Total: ${standardExercises.length} exercises in catalog`);
  } catch (error) {
    console.error('[SEED ERROR] Failed to seed exercises:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedExercises();
